### ISSUE TITLE
MASSIVE - First pass on texture for Bone Material

### ISSUE THREAD

**Issue by Silentnight18** [ZachArtHunter/fire-pack#7]
Below is a list for textures to be linked to their proper CustomModelData values. These are for the Bone Material items. All file paths have been included for every image, minus the wwwwwwwwwwww/eeeeeeeeeeeeeee parts. All CustomModelData has also been set and linked on the Items Sheet google doc spreadsheet.

Basic Horn 1
CustomModelData: 1
Filepath: /looticons/LootIcons_png/transparent/tusk_t_01.png
Basic Horn 2
CustomModelData: 2
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_02_t.png
Basic Horn 3
CustomModelData: 3
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_25_t.png
Basic Horn 4
CustomModelData: 4
Filepath: /looticons/LootIcons_png/transparent/Revantusk_t_01.png
Basic Horn 5
CustomModelData: 5
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_128_t.png
Basic Horn 6
CustomModelData: 6
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_100_t.png
Basic Horn 7
CustomModelData: 7
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_40_t.png
Basic Horn 8
CustomModelData: 8
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_124_t.png
Basic Horn 9
CustomModelData: 9
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_98_t.png
Curved Horn 1
CustomModelData: 10
Filepath: /looticons/LootIcons_png/transparent/horn_t_01.png
Curved Horn 2
CustomModelData: 11
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_77_t.png
Curved Horn 3
CustomModelData: 12
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_89_t.png
Antler Horn 1
CustomModelData: 13
Filepath: /looticons/LootIcons_png/transparent/horn_t_02.png
Antler Horn 2
CustomModelData: 14
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_07_t.png
Basic Tooth
CustomModelData: 15
Filepath: /looticons/LootIcons_png/transparent/tooth_t_01.png
Basic Jaw 1
CustomModelData: 16
Filepath: /looticons/LootIcons_png/transparent/jaw_t_01.png
Basic Jaw 2
CustomModelData: 17
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_47_t.png
Basic Jaw 3
CustomModelData: 18
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_33_t.png
Basic Jaw 4
CustomModelData: 19
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_59_t.png
Basic Ribcage 1
CustomModelData: 20
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_22_t.png
Basic Ribcage 2
CustomModelData: 21
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_15_t.png
Bird Skull 1
CustomModelData: 22
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_64_t.png
Bird Skull 2
CustomModelData: 23
Filepath: /foresticons/ForestIcons_transparent/ForestIcons_64_t.png
Rat Skull
CustomModelData: 24
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_12_t.png
Half Bone
CustomModelData: 25
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_27_t.png
Bone Pile
CustomModelData: 26
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_18_t.png
Bone Fragment
CustomModelData: 27
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_11_t.png
Leg Joint
CustomModelData: 28
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_86_t.png
Basic Claw 1
CustomModelData: 29
Filepath: /looticons/LootIcons_png/transparent/clutches_t_01.png
Basic Claw 2
CustomModelData: 30
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_03_t.png
Basic Claw 3
CustomModelData: 31
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_50_t.png
Basic Claw 4
CustomModelData: 32
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_81_t.png
Basic Claw 5
CustomModelData: 33
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_41_t.png
Basic Claw 6
CustomModelData: 34
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_72_t.png
Purple Bird Claw
CustomModelData: 35
Filepath: /looticons/LootIcons_png/transparent/paw_t_01.png
Blue Bird Claw
CustomModelData: 36
Filepath: /looticons/LootIcons_png/transparent/paw_t_02.png
Basic Pincer 1
CustomModelData: 37
Filepath: /looticons/LootIcons_png/transparent/chela_t_01.png
Basic Pincer 2
CustomModelData: 38
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_51_t.png
Basic Bug Arm 1
CustomModelData: 39
Filepath: /looticons/LootIcons_png/transparent/bgl_t_01.png
Basic Bug Legs 1
CustomModelData: 40
Filepath: /looticons/LootIcons_png/transparent/lpp_t_01.png
Yellow Bug Leg
CustomModelData: 41
Filepath: /looticons/LootIcons_png/transparent/leg_t_01.png
Insect Parts
CustomModelData: 42
Filepath: /looticons/LootIcons_png/transparent/insect_parts_t_01.png
Basic Hoof
CustomModelData: 43
Filepath: /looticons/LootIcons_png/transparent/lpp_t_01.png
Green Finger
CustomModelData: 44
Filepath: /looticons/LootIcons_png/transparent/finger_t_01.png
Bird Beak
CustomModelData: 45
Filepath: /looticons/LootIcons_png/transparent/clv_t_01.png

**Comment by ZachArtHunter** [comment]
Added 20m7d3a beta branch.
