### ISSUE TITLE
MASSIVE - first pass on textures for Rotten Flesh Material

### ISSUE THREAD

**Issue by Silentnight18** [ZachArtHunter/fire-pack#8]
Below is a list for textures to be linked to their proper CustomModelData values. These are for the Rotten Flesh Material items. All file paths have been included for every image, minus the wwwwwwwwwwww/eeeeeeeeeeeeeee parts. All CustomModelData has also been set and linked on the Items Sheet google doc spreadsheet.

Zombie Left Arm
CustomModelData: 1
Filepath: Zach
Zombie Right Arm
CustomModelData: 2
Filepath: Zach
Zombie Left Leg
CustomModelData: 3
Filepath: Zach
Zombie Right Leg
CustomModelData: 4
Filepath: Zach
Zombie Head
CustomModelData: 5
Filepath: Zach
Basic Eye 1
CustomModelData: 6
Filepath: /looticons/LootIcons_png/transparent/eye_t_01.png
Basic Eye 2
CustomModelData: 7
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_55_t.png
Basic Eye 3
CustomModelData: 8
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_49_t.png
Basic Eye 4
CustomModelData: 9
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_83_t.png
Slab of flesh 1
CustomModelData: 10
Filepath: /looticons/LootIcons_png/transparent/flesh_t_01.png
Slab of flesh 2
CustomModelData: 11
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_38_t.png
Slab of flesh 3
CustomModelData: 12
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_24_t.png
Slab of flesh 4
CustomModelData: 13
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_121_t.png
Slab of flesh 5
CustomModelData: 14
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_108_t.png
Slab of flesh 6
CustomModelData: 15
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_84_t.png
Basic Heart 1
CustomModelData: 16
Filepath: /looticons/LootIcons_png/transparent/heart_t_01.png
Basic Heart 2
CustomModelData: 17
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_97_t.png
Basic Organ 1
CustomModelData: 18
Filepath: /looticons/LootIcons_png/transparent/lvlr_t_01.png
Basic Organ 2
CustomModelData: 19
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_44_t.png
Basic Brain 1
CustomModelData: 20
Filepath: /looticons/LootIcons_png/transparent/brain_t_01.png
Basic Brain 2
CustomModelData: 21
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_48_t.png
Basic Tounge 1
CustomModelData: 22
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_60_t.png
Basic Guts
CustomModelData: 23
Filepath: /looticons/LootIcons_png/transparent/bowels_t_01.png
Bear Paw 1
CustomModelData: 24
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_43_t.png
Bear Paw 2
CustomModelData: 25
Filepath: /looticons/LootIcons_png/transparent/paw_t_03.png
Brown Fur Tail
CustomModelData: 26
Filepath: /looticons/LootIcons_png/transparent/paw_t_04.png
White Fur Tail
CustomModelData: 27
Filepath: /looticons/LootIcons_png/transparent/paw_t_05.png
Wolf Paw
CustomModelData: 28
Filepath: /looticons/LootIcons_png/transparent/paw_t_06.png
Scorpion Tail
CustomModelData: 29
Filepath: /looticons/LootIcons_png/transparent/tail_t_04.png
Rat Tail
CustomModelData: 30
Filepath: /looticons/LootIcons_png/transparent/tail_t_05.png
Lizard Tail
CustomModelData: 31
Filepath: /huntingicons/HuntingIcons_transparent/HuntingIcons_46_t.png

**Comment by ZachArtHunter** [comment]
Added in 20m7d3b.
